; Formal Documentation:
; https://docs.platformio.org/page/projectconf.html

; when hitting build, default to build sensor node
[platformio]
default_envs = sensor_node

; settings we want for both sensor and viewing nodes
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200  ; most common communication speed
lib_deps =  bblanchon/ArduinoJson @ ^7.0.0  ; both nodes should understand JSON
            mikem/RadioHead @ ^1.120 ; both will have radio comms

; sensor node settings (inherited from env)
[env:sensor_node]
build_flags = -D NODE_TYPE_SENSOR

; viewing node settings (inherited from env)
[env:viewing_node]
build_flags = -D NODE_TYPE_VIEWER
board_build.filesystem = littlefs  ; store index.html in a separate section
board_build.partitions = huge_app.csv  ; default flash storage partition is not 
                                       ; large enough for the web server library
