name: PlatformIO

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: karniv00l/platformio-run-action@v1
        with:
          environments: "sensor_node,viewing_node"
          project-conf: "./platformio.ini"
          silent: false
          verbose: true
          
